

###

POST http://localhost:9001/sub
Content-Type: application/json

{
  "topic": "/read/1/berlin",
  "function": "read1berlin",
  "location": {
    "lat" : 0.0,
    "lon" : 0.0,
    "radius": 2.0
  }
}

###
POST http://localhost:9001/sub
Content-Type: application/json

{
  "topic": "sieve",
  "function": "sieve",
  "location": {
    "lat" : 0.0,
    "lon" : 0.0,
    "radius": 2.0
  }
}

###

POST http://localhost:9001/sub
Content-Type: application/json

{
  "topic": "/TinyFaaSClient_read1berlin_52432051549791/52439417624291",
  "function": "read1berlin",
  "location": {
    "lat" : 0.0,
    "lon" : 0.0,
    "radius": 2.0
  }
}