###
POST http://localhost:8000/multi
Content-Type: application/json

{
  "topic":"info",
  "location":{"lon":0.0,"lat":0.0},
  "message":{
    "Temperature":5.0,
    "speed":20.0,
    "wind":20.0,
    "wet":8.0
  }
}

