POST http://192.168.0.125:8000/test
Content-Type: application/json

{
  "topic":"read",
  "location":{"lon":0.0,"lat":0.0},
  "message":{
    "temperature":55.0,
    "speed":20.0,
    "wind":20.0,
    "wet": 30.0
  }
}

